name: pylinter
author: Alexander Damiani
description: Lint python projects with flake8, mypy, and isort. The build will fail on violations.
branding:
  color: 'gray-dark'
  icon: 'check-circle'

inputs:
  python-root:
    description: 'directory to run linting on'
    required: false
    default: '.'
  flake8-flags:
    description: 'flake8 flags'
    required: false
    default: ''
  mypy-flags:
    description: 'mypy flags'
    required: false
    default: ''
  fail-on-isort:
    description: 'optional exit on isort errors'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.python-root }}
    - ${{ inputs.flake8-flags }}
    - ${{ inputs.mypy-flags }}
    - ${{ inputs.fail-on-isort }}
